# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: memory_trace.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12memory_trace.proto\x12\x0cmemory_trace\"8\n\x0bMemoryTrace\x12)\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x19.memory_trace.MemoryEvent\"\x92\x01\n\x0bMemoryEvent\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x11\n\tthread_id\x18\x02 \x01(\r\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\x04\x12#\n\x06mem_op\x18\x04 \x01(\x0e\x32\x13.memory_trace.MemOp\x12\'\n\x08hit_miss\x18\x05 \x01(\x0e\x32\x15.memory_trace.HitMiss*\x1c\n\x05MemOp\x12\x08\n\x04READ\x10\x00\x12\t\n\x05WRITE\x10\x01*\x1c\n\x07HitMiss\x12\x07\n\x03HIT\x10\x00\x12\x08\n\x04MISS\x10\x01\x42\x03\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'memory_trace_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\370\001\001'
  _MEMOP._serialized_start=243
  _MEMOP._serialized_end=271
  _HITMISS._serialized_start=273
  _HITMISS._serialized_end=301
  _MEMORYTRACE._serialized_start=36
  _MEMORYTRACE._serialized_end=92
  _MEMORYEVENT._serialized_start=95
  _MEMORYEVENT._serialized_end=241
# @@protoc_insertion_point(module_scope)
